version: "3.9"
services:
  ganache:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_VERSION=hydrogen # Put the version of node you want here
        - GANACHE_VERSION=7.9.1 # Put the version of ganache you want here
    ports:
      - "8545:8545"
      - "8546:8546"
    expose:
      - 8545
      - 8546
    volumes:
      - ./ganache:/var/ganache
    restart: unless-stopped

